executable_file = part_3
c_file = /home/gihad/Documents/roguelike_using_ncurses/part_3/part_3.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
