executable_file = part_17
c_file = /home/gihad/Documents/roguelike_using_ncurses/part_17/part_17.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
