executable_file = part_1
c_file = /home/gihad/Documents/roguelike_using_ncurses/part_1/part_1.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
