executable_file = part_12
c_file = /home/gihad/Documents/roguelike_using_ncurses/part_12/part_12.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
