executable_file = part_11
c_file = /home/gihad/Documents/roguelike_using_ncurses/part_11/part_11.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
