executable_file = part_13
c_file = /home/gihad/Documents/roguelike_using_ncurses/part_13/part_13.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
