executable_file = part_15
c_file = /home/gihad/Documents/roguelike_using_ncurses/part_15/part_15.c


all:
	gcc -o $(executable_file) $(c_file) -lncurses

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)
